version: "3"

services:

  api:
    build: .
    container_name: api
    ports:
      - "3000:3000"   # api
      - "8000:8000"   # debug
      - "35730:35730"   # livereload
    entrypoint: ["java", "-Xdebug", "-Xrunjdwp:server=y,transport=dt_socket,suspend=n,address=*:8000", "-jar", "sample-api.jar"]

  vscode:
    container_name: vscode
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
      - home:/home
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  home: